### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by cryptopool-builders** [barrystyle/yiimp-randomx#1]
trying to track it down but seems there is a massive memory leak in this build. I am running dedicated ports and tried https://github.com/tpruvot/yiimp/pull/284/files but no luck. 

Ill report back when I can debug it more

Thanks for all your hard work!

**Comment by barrystyle** [comment]
The RandomX verifier requires 2.3gb of ram for the virtual machine it 
creates; there is no memory leak.

**Comment by cryptopool-builders** [comment]
ahh i missed that requirement :)
